language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-clock-frontend' ]; then cd .. && eval "mv $currentfolder generator-clock-frontend" && cd generator-clock-frontend; fi

